'use client';
import {useCallback,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {LayoutDashboard,Building2,Users,Send,Mail,Waypoints,Bot,Plug,Settings,ScrollText,Search,Plus,ShieldAlert,Pause,Play,Check,ChevronRight} from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
const NAV=[['overview','Overview',LayoutDashboard],['companies','Companies',Building2],['contacts','Contacts',Users],['campaigns','Campaigns',Send],['email-review','Email review',Mail],['pipeline','Pipeline',Waypoints],['agent','Agent control',Bot],['integrations','Integrations',Plug],['settings','Settings',Settings],['activity','Activity logs',ScrollText]] as const;
type Obj=Record<string,any>;
export default function Dashboard({section}:{section:string}){const router=useRouter();const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const api=useCallback(async(path:string,opts:RequestInit={})=>{const csrf=sessionStorage.getItem('csrf')||'';const r=await fetch(`${API}${path}`,{credentials:'include',...opts,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...opts.headers}});if(r.status===401){router.push('/');throw new Error('Session expired')};const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'Action could not be completed');return d},[router]);
 const load=useCallback(async()=>{setError('');try{const map:Obj={overview:'/api/overview',companies:'/api/companies',contacts:'/api/contacts',campaigns:'/api/campaigns','email-review':'/api/drafts',pipeline:'/api/drafts',agent:'/api/agent',integrations:'/api/integrations',settings:'/api/agent',activity:'/api/activity'};setData(await api(map[section]||'/api/overview'))}catch(e){setError(e instanceof Error?e.message:'Unable to load')}},[api,section]);useEffect(()=>{load()},[load]);
 async function action(path:string,body?:Obj,method='POST'){setBusy(true);setError('');try{await api(path,{method,body:body?JSON.stringify(body):undefined});await load()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}}
 const title=NAV.find(n=>n[0]===section)?.[1]||'Overview';return <div className="shell"><aside><a className="brand" href="/overview"><span>G</span><strong>GiftReach</strong></a><nav>{NAV.map(([id,label,Icon])=><a key={id} href={`/${id}`} className={section===id?'active':''}><Icon size={17}/>{label}</a>)}</nav><div className="rail-foot"><span className="status-dot"/>Safe mock mode<small>Real sending is off</small></div></aside><main className="workspace"><header className="top"><div><p>Corporate gifting outreach</p><h1>{title}</h1></div><div className="top-actions"><button className="icon"><Search size={18}/><span>Search</span></button><div className="avatar">PV</div></div></header>{error&&<div className="alert">{error}<button onClick={load}>Try again</button></div>}<section className="content">{data===null?<div className="loading">Loading workspace…</div>:<View section={section} data={data} action={action} busy={busy}/>}</section></main></div>}
function View({section,data,action,busy}:{section:string,data:any,action:(p:string,b?:Obj,m?:string)=>void,busy:boolean}){
 if(section==='overview')return <><div className="agent-strip"><div><span className="pulse"/><p>Agent mode</p><strong>{data.agent.mode.replaceAll('_',' ')}</strong></div><p>{data.agent.paused?'Operations are paused.':'Safety controls are active. No real messages are sent in mock mode.'}</p><a href="/agent">Open controls <ChevronRight size={16}/></a></div><div className="metrics">{[['Companies',data.companies],['Contacts',data.contacts],['Verified',data.verified],['Awaiting review',data.drafts],['Sent',data.sent],['Replies',data.replies],['Bounces',data.bounces],['Interested',data.interested]].map(([k,v])=><article key={k}><span>{k}</span><strong>{v}</strong></article>)}</div><Empty title="Begin with a known company" copy="Add a company and record where you found it. GiftReach will keep every contact tied to its source." action="Add company" href="/companies"/></>;
 if(section==='companies')return <><PageTools label="Add company"/><Table headers={['Company','Industry','Location','Score','Contacts','State']} rows={data.map((x:Obj)=>[x.name,x.industry||'Not recorded',`${x.city}, ${x.district}`,`${x.score}/100`,x.contact_count,x.suppressed?'Suppressed':'Eligible'])}/>{!data.length&&<Empty title="No companies yet" copy="Add a company with genuine source evidence or import a permitted list." action="Add first company"/>}</>;
 if(section==='contacts')return <><PageTools label="Add contact"/><Table headers={['Contact','Company','Role','Verification','Source','State']} rows={data.map((x:Obj)=>[x.name||x.email,x.company,x.title||'Not recorded',x.verification_status,x.sources[0]?.source_type||'Missing',x.suppressed?'Suppressed':'Eligible'])}/>{!data.length&&<Empty title="No contacts yet" copy="Every email needs a source. Founder-provided addresses are welcome and clearly labelled." action="Add contact"/>}</>;
 if(section==='campaigns')return <><PageTools label="Create campaign"/><Table headers={['Campaign','Status','Daily cap','Hourly cap','Contacts / company']} rows={data.map((x:Obj)=>[x.name,x.status,x.daily_limit,x.hourly_limit,x.max_contacts_per_company])}/>{!data.length&&<Empty title="No campaigns" copy="Create a focused campaign with explicit geography, roles, and conservative limits." action="Create campaign"/>}</>;
 if(section==='email-review')return <><div className="review-head"><p>{data.length} drafts</p><span>Every draft must pass policy before approval.</span></div>{data.map((d:Obj)=><article className="draft" key={d.id}><div><span>{d.status}</span><h3>{d.subject}</h3><p>{d.body.slice(0,180)}…</p>{d.validation_errors?.length>0&&<em>{d.validation_errors.join(' · ')}</em>}</div><div><button disabled={busy||d.validation_errors?.length} onClick={()=>action(`/api/drafts/${d.id}/approve`)}><Check size={16}/>Approve</button><button disabled={busy||d.status!=='APPROVED'} onClick={()=>action(`/api/drafts/${d.id}/send`)}>Send eligible</button></div></article>)}{!data.length&&<Empty title="Review queue is clear" copy="Generated drafts will appear here with their validation results and recipient provenance."/>}</>;
 if(section==='pipeline'){const stages=['DRAFT','APPROVED','SENT','REPLIED','INTERESTED','BOUNCED','SUPPRESSED'];return <div className="pipeline">{stages.map(s=><article key={s}><div><span>{s}</span><strong>{data.filter((d:Obj)=>d.status===s).length}</strong></div>{data.filter((d:Obj)=>d.status===s).map((d:Obj)=><p key={d.id}>{d.subject}</p>)}</article>)}</div>}
 if(section==='agent')return <><div className="control-hero"><div><span className={data.kill_switch?'danger-dot':'pulse'}/><p>Current mode</p><h2>{data.mode.replaceAll('_',' ')}</h2></div><button className="danger" disabled={busy} onClick={()=>action('/api/agent/emergency-stop')}><ShieldAlert size={18}/>Emergency stop</button></div><div className="controls"><article><h3>Operating mode</h3><p>Autopilot remains gated by verification, limits, suppression, and draft policy.</p><select value={data.mode} onChange={e=>action('/api/agent',{mode:e.target.value},'PATCH')}><option>OFF</option><option>RESEARCH</option><option>DRAFT</option><option>CONTROLLED_AUTOPILOT</option></select></article><article><h3>Global operation</h3><p>Pause all scheduled work without losing state.</p><button onClick={()=>action('/api/agent',{paused:!data.paused},'PATCH')}>{data.paused?<Play size={16}/>:<Pause size={16}/>} {data.paused?'Resume':'Pause'}</button></article><article><h3>Sending</h3><p>Keep sending independent from discovery and drafting.</p><button onClick={()=>action('/api/agent',{sending_paused:!data.sending_paused},'PATCH')}>{data.sending_paused?'Resume sending':'Pause sending'}</button></article></div></>;
 if(section==='integrations')return <div className="integrations">{Object.entries(data).map(([k,v]:[string,any])=><article key={k}><div className={`integration-icon ${v.status}`}><Plug size={18}/></div><div><h3>{k[0].toUpperCase()+k.slice(1)}</h3><p>{v.status.replaceAll('_',' ')}</p></div><span>{v.status==='connected'?'Ready':v.status==='mock'?'Development':'Setup needed'}</span></article>)}</div>;
 if(section==='settings')return <><div className="settings-grid"><article><h3>Approved catalogue</h3><p>Generation is restricted to these categories.</p><div className="chips">{data.approved_categories.map((x:string)=><span key={x}>{x}</span>)}</div></article><article><h3>Sending safeguards</h3><label>Daily maximum<input value={data.daily_limit} readOnly/></label><label>Hourly maximum<input value={data.hourly_limit} readOnly/></label></article><article><h3>Required signature</h3><pre>Pranav V.{`\n`}Corporate Gifting</pre></article></div></>;
 if(section==='activity')return <div className="activity">{data.map((x:Obj)=><article key={x.id}><span className="event-dot"/><div><strong>{x.message}</strong><p>{x.event} · {new Date(x.created_at).toLocaleString()}</p></div></article>)}{!data.length&&<Empty title="No activity recorded" copy="Agent runs, manual actions, failures, and sends will be recorded here."/>}</div>;
 return <Empty title="Nothing here yet" copy="This workspace is ready for data."/>}
function Table({headers,rows}:{headers:string[],rows:any[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function PageTools({label}:{label:string}){return <div className="tools"><div className="searchbox"><Search size={16}/><input placeholder="Search records"/></div><button disabled title="Use the API or setup workflow in this MVP"><Plus size={16}/>{label}</button></div>}
function Empty({title,copy,action,href}:{title:string,copy:string,action?:string,href?:string}){return <div className="empty"><div className="empty-mark">G</div><h2>{title}</h2><p>{copy}</p>{action&&(href?<a href={href}>{action}</a>:<button disabled title="Available through the API">{action}</button>)}</div>}
